# Generated by Django 5.2.15 on 2026-07-05 19:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_menutag_promotion_discount_menuitem_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Green Studio Кофейня', max_length=120, verbose_name='Название')),
                ('topbar_text', models.CharField(default='Кофе, уют и тишина — добро пожаловать в Green Studio Кофейня', max_length=220, verbose_name='Текст в шапке')),
                ('phone', models.CharField(default='+7 905 000 64 17', max_length=30, verbose_name='Телефон')),
                ('address_name', models.CharField(default='Green Studio Кофейня', max_length=100, verbose_name='Название в футере')),
                ('address_street', models.CharField(default='ул. Артема 151', max_length=200, verbose_name='Адрес')),
                ('hours_weekday', models.CharField(default='Пн – Пт: 9:00 – 21:00', max_length=80, verbose_name='Будни')),
                ('hours_weekend', models.CharField(default='Сб – Вс: 10:00 – 20:00', max_length=80, verbose_name='Выходные')),
                ('footer_tagline', models.CharField(default='С любовью на Артема 151', max_length=120, verbose_name='Слоган футера')),
                ('hero_tagline', models.CharField(default='С любовью на Артема 151', max_length=120, verbose_name='Тег на главном экране')),
                ('hero_title_line1', models.CharField(default='Место, где', max_length=80, verbose_name='Заголовок hero, строка 1')),
                ('hero_title_line2', models.CharField(default='всё продумано', max_length=80, verbose_name='Заголовок hero, строка 2')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Скидка для привязанных позиций меню.', max_digits=5, verbose_name='Скидка, %'),
        ),
    ]
