# Generated by Django 5.2.14 on 2026-07-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_gallery_aspect_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address_street',
            field=models.CharField(default='ул. Артема 151', max_length=200, verbose_name='Адрес'),
        ),
    ]
